# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' an altrep object that wraps a arma::dvec
#'
#' @export
doubles <- function() {
    .Call(`_shvecr_doubles`)
}

doubles_example <- function() {
    .Call(`_shvecr_doubles_example`)
}

create_vec3 <- function(mem, length, type) {
    .Call(`_shvecr_create_vec3`, mem, length, type)
}

