# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

new_altreal <- function(name, length, type) {
    .Call(`_shvecr_new_altreal`, name, length, type)
}

create_vec3 <- function(mem, length, type) {
    .Call(`_shvecr_create_vec3`, mem, length, type)
}

